### ISSUE TITLE
mistnet_optimizer asks for 'xtimes' instead of 'xtime' from network$optimization_results 

### ISSUE THREAD

**Issue by gaiteiro** [davharris/mistnet#116]
In mistnet_optimizer we have:

  opt = optimx::optimx(par = unlist(network$par_list), fn = fn, 
      gr = gr, method = method, itnmax = itnmax, control = control, 
      hessian = hessian, ...)
  network$optimization_results = c(opt[c("value", "fevals", 
      "gevals", "niter", "convcode", "xtimes")], structure(c(attr(opt, 
      "details")), names = colnames(attr(opt, "details"))))

....but looking at opt I see 'xtime' instead of 'xtimes' - so the second line throws an unused argument error: 
Maximizing -- use negfn and neggr
Error in `[.data.frame`(opt, c("value", "fevals", "gevals", "niter", "convcode",  :  undefined columns selected

Seems to work after I had a look in mistnet_fit_optimx and changed xtimes to xtime. FYI: I'm re-running the SDM comparison scripts of Norberg et al (https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecm.1370) - from https://doi.org/10.5281/zenodo.2637812 (fit.mistnet.r)

Apologies if I should be providing more info....? I'm very new to this.

**Comment by davharris** [comment]
Hi, looks like the developers of `optimx` changed their package. https://github.com/GeoBosh/Countr/issues/1

You could either change xtime/xtimes in the mistnet code or you could downgrade to a version of `optimx` from before 2018-7.10.

Hope this helps!

**Comment by gaiteiro** [comment]
Thanks! - changing the mistnet code worked.
